name: "Main workflow"
on: [pull_request, push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
      - name: "Install dependencies"
        run: yarn
      - name: "Build application"
        run: yarn dist
      - name: "Archive build artifacts"
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.run_id }}
          overwrite: true
          file_glob: true